[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirigir las llamadas al proxy a la funci√≥n serverless
[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/proxy-resource"
  to = "/.netlify/functions/proxy-resource"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
